### ISSUE TITLE
Support for GitHub Pull Request comment webhook inside the Github Provider

### ISSUE THREAD

**Issue by pablocarmu** [bitrise-io/bitrise-webhooks#116]
Hi folks!

I plan to add support for the _Pull Request comment webhook_ inside the Github Provider.

The idea is to trigger an action when the webhook receives a [pull_request_review_comment](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request_review_comment) call.

The reasoning behind this is that we want to trigger workflows by posting comments inside the PR, like

```
Please trigger new build
```

or

```
Please unit test
```

Ideally, it will provide a new `trigger` inside the `trigger_map` so people can customize it inside their `Bitrise.yml`

```
trigger_map:
- pull_request_review_comment: Please create new build
  workflow:  pull_request_build_app
- pull_request_review_comment: Please unit test
  workflow:  pull_request_unit_tests
```

in case we want to differentiate when a comment has been created, edited, or deleted we can have the following filters
```
- pull_request_review_comment_created
- pull_request_review_comment_edited
- pull_request_review_comment_deleted
```

I want to check if this is something you'll find interesting to be added to the GitHub provider?
I'm open to discussing implementation details, how to make it more generic, or anything you'll like to discuss!

Have a good day team!
